mode: rule
mixed-port: 7890
allow-lan: true
log-level: info
ipv6: false
tun:
  enable: false
  stack: gvisor
  auto-route: false
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  - 9.9.9.9
  fallback:
  - tls://8.8.8.8
  - tls://1.1.1.1
proxies:
- name: 🇳🇱 NL [R][xhttp] | 91.84.117.29
  type: vless
  server: 91.84.117.29
  port: 443
  uuid: a4037b4c-6a9d-528c-9efb-7d801cce8adb
  udp: true
  skip-cert-verify: true
  network: xhttp
  encryption: none
  tls: true
  reality-opts:
    public-key: PyV8IrAs0LkE2d_DdjvdCtpWG7MZyUKsYkb52GUmuDM
    short-id: '67'
  servername: vk.com
  client-fingerprint: chrome
- name: 🇩🇪 DE [R][grpc] | de-3.coinbridge.nl
  type: vless
  server: de-3.coinbridge.nl
  port: 443
  uuid: b0f08ae1-7cf9-4612-ad61-72681e0b92da
  udp: true
  skip-cert-verify: true
  network: grpc
  encryption: none
  tls: true
  reality-opts:
    public-key: kPBXTe2KCp55GrHS_qU_sF7ohUcT8Vu-e8i6Yd9MERI
    short-id: d5c7f84e37e0c12d
  servername: google.com
  client-fingerprint: random
  grpc-opts:
    grpc-service-name: data-sync
- name: 🇺🇸 US [R] | 94.139.251.23
  type: vless
  server: 94.139.251.23
  port: 443
  uuid: 35699c54-9188-4f43-972e-e8e42dbb104e
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 6ycuxfrEPsqE9eXZ5_Osbnx4g6hXWmkc8pFuAJkJ4jY
  servername: apple.com
  flow: xtls-rprx-vision
  client-fingerprint: qq
- name: 🇳🇱 NL [R] | ruded2.onlinestreamself.com
  type: vless
  server: ruded2.onlinestreamself.com
  port: 443
  uuid: 35699c54-9188-4f43-972e-e8e42dbb104e
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: M9_R2DX7bxoMJpkF4RcyJ0oJ8ZuGsxWrjuREKi6Ol0w
  servername: apple.com
  flow: xtls-rprx-vision
  client-fingerprint: qq
- name: 🇳🇱 NL [R] | ruded3.onlinestreamself.com
  type: vless
  server: ruded3.onlinestreamself.com
  port: 443
  uuid: 35699c54-9188-4f43-972e-e8e42dbb104e
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 6ycuxfrEPsqE9eXZ5_Osbnx4g6hXWmkc8pFuAJkJ4jY
  servername: apple.com
  flow: xtls-rprx-vision
  client-fingerprint: qq
- name: 🇳🇱 NL [R] | ruded1.onlinestreamself.com
  type: vless
  server: ruded1.onlinestreamself.com
  port: 443
  uuid: 35699c54-9188-4f43-972e-e8e42dbb104e
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: m_Xgh5XeqmN9JaDxkct4yTup2YPVxCV5fGnUnMZ3pWE
  servername: apple.com
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇺🇸 US [R] | 94.139.251.189
  type: vless
  server: 94.139.251.189
  port: 443
  uuid: 35699c54-9188-4f43-972e-e8e42dbb104e
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: m_Xgh5XeqmN9JaDxkct4yTup2YPVxCV5fGnUnMZ3pWE
  servername: apple.com
  flow: xtls-rprx-vision
  client-fingerprint: qq
- name: 🇬🇧 GB [R] | 144.31.87.16
  type: vless
  server: 144.31.87.16
  port: 443
  uuid: c40f773e-3b96-417e-b22c-e48cb63ca7d9
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: l5eAOSPQMEyzEPvWGAKvCkcPpsJvR3DJfYo6elw1UTE
    short-id: 3b802dad547b0847
  servername: yandex.ru
  client-fingerprint: firefox
- name: 🇰🇿 KZ [R] | raff-vpn-kz-server1.ru
  type: vless
  server: raff-vpn-kz-server1.ru
  port: 443
  uuid: 6fdfdb73-51b0-4a14-89a5-c9355a0e0397
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: vCxfuNNmogA1DlPkjvmKb7_hSgXqe4MboPfi2s1JZG0
    short-id: b318242471ba4f5b
  servername: google.com
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇩🇪 DE [R][xhttp] | 196.240.57.50
  type: vless
  server: 196.240.57.50
  port: 443
  uuid: 6f98a077-004e-4b86-8b78-8d09308d3868
  udp: true
  skip-cert-verify: true
  network: xhttp
  encryption: none
  tls: true
  reality-opts:
    public-key: XBBVeMURFu7jmYJ9MZwjEWgfQlGTnRs0B5So5Fy7jWs
    short-id: 992f3294e2336744
  servername: stats.vk-portal.net
  client-fingerprint: chrome
- name: 🇩🇪 DE [R] | 82.202.141.2
  type: vless
  server: 82.202.141.2
  port: 443
  uuid: 434d057f-83cf-4091-8985-0e09984a645f
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: -3a4R4WIvLor7WHxXIFL98FA1KFzHuqU1Z6R6JEVnU8
    short-id: ad27a4d1
  servername: ya.ru
  flow: xtls-rprx-vision
  client-fingerprint: firefox
- name: 🇵🇱 PL [R] | 81.90.17.164
  type: vless
  server: 81.90.17.164
  port: 443
  uuid: cb784d00-d34a-4389-b938-8717f7b28353
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: v0XQn6uvyC8q5CThcRYLer1F1OOYpZDn5NLOvDicaWg
    short-id: b31c2b75add2e5fa
  servername: yastatic.net
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇫🇮 FI [R] | node-tw0.omhvp.co
  type: vless
  server: node-tw0.omhvp.co
  port: 443
  uuid: a8f84171-5f96-4547-b621-59758fe668c8
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: jWVk2Z7eFkyDcu2xgzqX8JsPbZuCVhHUWD463Vfgazw
    short-id: 7a5b89ecdb01f781
  servername: sun6-21.userapi.com
  flow: xtls-rprx-vision
  client-fingerprint: firefox
- name: 🇳🇱 NL [R] | nl4.wireguardvpnbotik.com
  type: vless
  server: nl4.wireguardvpnbotik.com
  port: 443
  uuid: c35474ed-d6a8-4213-8edb-5c333e5b5f7c
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: Qd_xkVSBMEUP48r5m-yaziTq1aZQyFSJ19Y0qp9d4nM
    short-id: 8d37130b315d37da
  servername: sun1-19.userapi.com
  flow: xtls-rprx-vision
  client-fingerprint: qq
- name: 🇫🇷 FR [R] | 45.192.2.115
  type: vless
  server: 45.192.2.115
  port: 443
  uuid: 0b8dfc50-9e2d-4b3c-85cd-870b478312a0
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 1oUeBtHH4DskTM_jCh-6enWRkFMDX9l1OU5kWYl4kxA
    short-id: f34818a561dfd1fe
  servername: yandex.net
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇫🇷 FR [R] | 45.192.2.173
  type: vless
  server: 45.192.2.173
  port: 443
  uuid: 1478d83f-3e0b-4d96-99cc-b514495e53c6
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 1oUeBtHH4DskTM_jCh-6enWRkFMDX9l1OU5kWYl4kxA
    short-id: 364994a6f61fc955
  servername: yandex.net
  flow: xtls-rprx-vision
  client-fingerprint: firefox
- name: 🇫🇷 FR [R] | 45.192.2.51
  type: vless
  server: 45.192.2.51
  port: 443
  uuid: e9346960-a429-4c1a-b661-512611450fea
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 1oUeBtHH4DskTM_jCh-6enWRkFMDX9l1OU5kWYl4kxA
    short-id: ece180c605b5453c
  servername: yandex.net
  flow: xtls-rprx-vision
- name: 🇧🇬 BG [R] | 93.152.223.98
  type: vless
  server: 93.152.223.98
  port: 443
  uuid: 0b9bcbc1-b289-4a64-86fa-a5b731b65384
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: QocXHwad0mV7WA5jSAcqDac3uuVBEp1WF775-CilniE
    short-id: 45ba18f429ad1f28
  servername: web.max.ru
  flow: xtls-rprx-vision
- name: 🇳🇱 NL [R] | 193.233.126.104
  type: vless
  server: 193.233.126.104
  port: 443
  uuid: b12eebc2-369c-4f3c-96a0-a8bd150ca8d5
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: Lxs8Ruv2zHH0XW5EiQmuCaScfkGPCxWjW02YDWH8pyU
    short-id: eb0cca7312345678
  servername: 00.img.avito.st
  flow: xtls-rprx-vision
  client-fingerprint: firefox
- name: 🇪🇪 EE [R] | est.vrsvpn.com
  type: vless
  server: est.vrsvpn.com
  port: 443
  uuid: 0b9bcbc1-b289-4a64-86fa-a5b731b65384
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: SJkDT_L0eziQR2afDGrkN7-uRxjYu6bZxIGXlKeCvX4
    short-id: 15aa18f971da1f81
  servername: web.max.ru
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇪🇪 EE [R] | 185.155.97.241
  type: vless
  server: 185.155.97.241
  port: 443
  uuid: 0b9bcbc1-b289-4a64-86fa-a5b731b65384
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: SJkDT_L0eziQR2afDGrkN7-uRxjYu6bZxIGXlKeCvX4
    short-id: 15aa18f971da1f81
  servername: web.max.ru
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇫🇷 FR [R] | 45.192.2.51 (2)
  type: vless
  server: 45.192.2.51
  port: 443
  uuid: 44a6901d-6675-41b1-9a80-ee3308699e1d
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 1oUeBtHH4DskTM_jCh-6enWRkFMDX9l1OU5kWYl4kxA
    short-id: f34818a561dfd1fe
  servername: yandex.net
  flow: xtls-rprx-vision
- name: 🇫🇷 FR [R] | 45.192.2.51 (3)
  type: vless
  server: 45.192.2.51
  port: 443
  uuid: c9b764b5-49cf-4400-9540-f56f7c09a87a
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 1oUeBtHH4DskTM_jCh-6enWRkFMDX9l1OU5kWYl4kxA
    short-id: f34818a561dfd1fe
  servername: yandex.net
  flow: xtls-rprx-vision
  client-fingerprint: qq
- name: 🇫🇷 FR [R] | 45.192.2.157
  type: vless
  server: 45.192.2.157
  port: 443
  uuid: 5098e189-3462-4ff7-8ddd-4aaecfd060ea
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 1oUeBtHH4DskTM_jCh-6enWRkFMDX9l1OU5kWYl4kxA
    short-id: f34818a561dfd1fe
  servername: yandex.net
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇧🇬 BG [R] | de.vrsvpn.com
  type: vless
  server: de.vrsvpn.com
  port: 443
  uuid: 0b9bcbc1-b289-4a64-86fa-a5b731b65384
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: QocXHwad0mV7WA5jSAcqDac3uuVBEp1WF775-CilniE
    short-id: 45ba18f429ad1f28
  servername: web.max.ru
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇫🇷 FR [R] | 45.192.2.51 (4)
  type: vless
  server: 45.192.2.51
  port: 443
  uuid: 69080ad0-9074-4c38-b729-ace93fd4ac13
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 1oUeBtHH4DskTM_jCh-6enWRkFMDX9l1OU5kWYl4kxA
    short-id: 364994a6f61fc955
  servername: yandex.net
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇫🇷 FR [R] | 45.192.2.51 (5)
  type: vless
  server: 45.192.2.51
  port: 443
  uuid: 52f0f0ee-bc74-4757-8e1c-51e334233b4d
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 1oUeBtHH4DskTM_jCh-6enWRkFMDX9l1OU5kWYl4kxA
    short-id: 364994a6f61fc955
  servername: yandex.net
  flow: xtls-rprx-vision
- name: 🇱🇻 LV  | lv-ddc.astralweb.tech
  type: vless
  server: lv-ddc.astralweb.tech
  port: 443
  uuid: 3ad1d277-5715-4ca1-84db-5baea72f822d
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  servername: lv-ddc.astralweb.tech
  client-fingerprint: firefox
- name: 🇫🇷 FR  | 89.208.113.16
  type: vless
  server: 89.208.113.16
  port: 443
  uuid: adce7c2a-3191-49ae-b61c-9b8258ea1b0e
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
proxy-groups:
- name: 🚀 Auto
  type: url-test
  proxies:
  - 🇳🇱 NL [R][xhttp] | 91.84.117.29
  - 🇩🇪 DE [R][grpc] | de-3.coinbridge.nl
  - 🇺🇸 US [R] | 94.139.251.23
  - 🇳🇱 NL [R] | ruded2.onlinestreamself.com
  - 🇳🇱 NL [R] | ruded3.onlinestreamself.com
  - 🇳🇱 NL [R] | ruded1.onlinestreamself.com
  - 🇺🇸 US [R] | 94.139.251.189
  - 🇬🇧 GB [R] | 144.31.87.16
  - 🇰🇿 KZ [R] | raff-vpn-kz-server1.ru
  - 🇩🇪 DE [R][xhttp] | 196.240.57.50
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
- name: 🌍 Proxy
  type: select
  proxies:
  - 🚀 Auto
  - 🇳🇱 NL [R][xhttp] | 91.84.117.29
  - 🇩🇪 DE [R][grpc] | de-3.coinbridge.nl
  - 🇺🇸 US [R] | 94.139.251.23
  - 🇳🇱 NL [R] | ruded2.onlinestreamself.com
  - 🇳🇱 NL [R] | ruded3.onlinestreamself.com
  - 🇳🇱 NL [R] | ruded1.onlinestreamself.com
  - 🇺🇸 US [R] | 94.139.251.189
  - 🇬🇧 GB [R] | 144.31.87.16
  - 🇰🇿 KZ [R] | raff-vpn-kz-server1.ru
  - 🇩🇪 DE [R][xhttp] | 196.240.57.50
  - 🇩🇪 DE [R] | 82.202.141.2
  - 🇵🇱 PL [R] | 81.90.17.164
  - 🇫🇮 FI [R] | node-tw0.omhvp.co
  - 🇳🇱 NL [R] | nl4.wireguardvpnbotik.com
  - 🇫🇷 FR [R] | 45.192.2.115
  - 🇫🇷 FR [R] | 45.192.2.173
  - 🇫🇷 FR [R] | 45.192.2.51
  - 🇧🇬 BG [R] | 93.152.223.98
  - 🇳🇱 NL [R] | 193.233.126.104
  - 🇪🇪 EE [R] | est.vrsvpn.com
  - 🇪🇪 EE [R] | 185.155.97.241
  - 🇫🇷 FR [R] | 45.192.2.51 (2)
  - 🇫🇷 FR [R] | 45.192.2.51 (3)
  - 🇫🇷 FR [R] | 45.192.2.157
  - 🇧🇬 BG [R] | de.vrsvpn.com
  - 🇫🇷 FR [R] | 45.192.2.51 (4)
  - 🇫🇷 FR [R] | 45.192.2.51 (5)
  - 🇱🇻 LV  | lv-ddc.astralweb.tech
  - 🇫🇷 FR  | 89.208.113.16
- name: 🎯 Direct
  type: select
  proxies:
  - DIRECT
  - 🌍 Proxy
rules:
- MATCH,🌍 Proxy
