mode: rule
mixed-port: 7890
allow-lan: true
log-level: info
ipv6: false
tun:
  enable: false
  stack: gvisor
  auto-route: false
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  - 9.9.9.9
  fallback:
  - tls://8.8.8.8
  - tls://1.1.1.1
proxies:
- name: 🇳🇱 NL [R][xhttp] | 91.84.117.29
  type: vless
  server: 91.84.117.29
  port: 443
  uuid: a4037b4c-6a9d-528c-9efb-7d801cce8adb
  udp: true
  skip-cert-verify: true
  network: xhttp
  encryption: none
  tls: true
  reality-opts:
    public-key: PyV8IrAs0LkE2d_DdjvdCtpWG7MZyUKsYkb52GUmuDM
    short-id: '67'
  servername: vk.com
  client-fingerprint: chrome
- name: 🇫🇮 FI [R][grpc] | 31.129.42.239
  type: vless
  server: 31.129.42.239
  port: 443
  uuid: 97e967da-1d2b-439e-836b-a9d5a90496dc
  udp: true
  skip-cert-verify: true
  network: grpc
  encryption: none
  tls: true
  reality-opts:
    public-key: KwPeoAnP208rOsWWHSjhPKdpVzvIHpfBUltBHaBCSDs
    short-id: d9114354
  servername: vk.com
  client-fingerprint: firefox
  grpc-opts:
    grpc-service-name: grpc8c948083b439
- name: 🇬🇧 GB [R] | 144.31.87.16
  type: vless
  server: 144.31.87.16
  port: 443
  uuid: c40f773e-3b96-417e-b22c-e48cb63ca7d9
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: l5eAOSPQMEyzEPvWGAKvCkcPpsJvR3DJfYo6elw1UTE
    short-id: 3b802dad547b0847
  servername: yandex.ru
  client-fingerprint: firefox
- name: 🇬🇧 GB [R] | 95.85.224.51
  type: vless
  server: 95.85.224.51
  port: 443
  uuid: 342ab7e4-5a89-0001-8809-304120d4aa83
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: WWeAHWUVD-phmnjNJ823cer0c4CMIbEs08AhsuEZmDc
    short-id: a696de84963656de
  servername: max.ru
  flow: xtls-rprx-vision
  client-fingerprint: qq
- name: 🇫🇮 FI [R][xhttp] | 2.27.42.180
  type: vless
  server: 2.27.42.180
  port: 443
  uuid: 5a266979-4249-4448-a93a-f27bb8aed542
  udp: true
  skip-cert-verify: true
  network: xhttp
  encryption: none
  tls: true
  reality-opts:
    public-key: -KEUMaLxpG99ZMuQLYI9sBYfM--Z50phY2CPYsj9Uz0
    short-id: 3da17f441e2aa777
  servername: cdn.yandex.ru
  client-fingerprint: firefox
- name: 🇳🇱 NL [R] | 46.243.232.122
  type: vless
  server: 46.243.232.122
  port: 443
  uuid: 8e85752d-c04f-427d-9d70-b10d144c8492
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: NMEX862Hl5C5RIv-SbSc76pkKbKdB_3nnkiaSNVOTG0
  servername: yastatic.net
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇳🇱 NL [R] | wl-1.myfreedom.rest
  type: vless
  server: wl-1.myfreedom.rest
  port: 443
  uuid: 6192b7d1-fc9d-4be1-900e-dbd69de95ddf
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: sdnD0vxmj8kHBOoVM8TE9IyBCGwnKNB8hZVaHp_Zfjk
    short-id: fe8d
  servername: ads.vk.ru
  flow: xtls-rprx-vision
  client-fingerprint: firefox
- name: 🇰🇿 KZ [R] | 5.180.40.9
  type: vless
  server: 5.180.40.9
  port: 443
  uuid: 5e19b3c8-c1dc-4163-95e2-895319c15d6c
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 06GvG7PU5F3Hgq-vUH24tU0tpsbGMCCt26BSvlaBNUE
    short-id: dfbfa87e9f37f1f0
  servername: cloud.mail.ru
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇰🇿 KZ [R] | 5.180.42.85
  type: vless
  server: 5.180.42.85
  port: 443
  uuid: 5e19b3c8-c1dc-4163-95e2-895319c15d6c
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 06GvG7PU5F3Hgq-vUH24tU0tpsbGMCCt26BSvlaBNUE
    short-id: dfbfa87e9f37f1f0
  servername: cloud.mail.ru
  flow: xtls-rprx-vision
  client-fingerprint: firefox
- name: 🇰🇿 KZ [R] | kz2.techdatacloud.org
  type: vless
  server: kz2.techdatacloud.org
  port: 443
  uuid: 5e19b3c8-c1dc-4163-95e2-895319c15d6c
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 06GvG7PU5F3Hgq-vUH24tU0tpsbGMCCt26BSvlaBNUE
    short-id: dfbfa87e9f37f1f0
  servername: cloud.mail.ru
  flow: xtls-rprx-vision
  client-fingerprint: firefox
- name: 🇩🇪 DE [ws] | 84.201.128.112
  type: vless
  server: 84.201.128.112
  port: 443
  uuid: 5ca83936-136d-4314-8453-4ba10a86cf60
  udp: true
  skip-cert-verify: true
  network: ws
  encryption: none
  tls: true
  servername: cloudflare.vhub.pro
  client-fingerprint: firefox
  ws-opts:
    path: /websocket?ed=2560
    headers:
      Host: cloudflare.vhub.pro
- name: 🇩🇪 DE [ws] | 158.160.196.224
  type: vless
  server: 158.160.196.224
  port: 443
  uuid: 5ca83936-136d-4314-8453-4ba10a86cf60
  udp: true
  skip-cert-verify: true
  network: ws
  encryption: none
  tls: true
  servername: cloudflare.vhub.pro
  client-fingerprint: firefox
  ws-opts:
    path: /websocket?ed=2560
    headers:
      Host: cloudflare.vhub.pro
- name: 🇫🇷 FR  | fr186.mechvpn.online
  type: vless
  server: fr186.mechvpn.online
  port: 443
  uuid: 53c76647-14d1-4df5-99cb-be99ad2e6bd9
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇩🇪 DE [ws] | 185.178.208.176
  type: vless
  server: 185.178.208.176
  port: 443
  uuid: 653aea5e-2157-4a1f-89bf-8b46fb677921
  udp: true
  skip-cert-verify: true
  network: ws
  encryption: none
  tls: true
  servername: stream.telemetryapi.uk
  client-fingerprint: firefox
  ws-opts:
    path: /api/v2/client/session/connect
    headers:
      Host: stream.telemetryapi.uk
proxy-groups:
- name: 🚀 Auto
  type: url-test
  proxies:
  - 🇳🇱 NL [R][xhttp] | 91.84.117.29
  - 🇫🇮 FI [R][grpc] | 31.129.42.239
  - 🇬🇧 GB [R] | 144.31.87.16
  - 🇬🇧 GB [R] | 95.85.224.51
  - 🇫🇮 FI [R][xhttp] | 2.27.42.180
  - 🇳🇱 NL [R] | 46.243.232.122
  - 🇳🇱 NL [R] | wl-1.myfreedom.rest
  - 🇰🇿 KZ [R] | 5.180.40.9
  - 🇰🇿 KZ [R] | 5.180.42.85
  - 🇰🇿 KZ [R] | kz2.techdatacloud.org
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
- name: 🌍 Proxy
  type: select
  proxies:
  - 🚀 Auto
  - 🇳🇱 NL [R][xhttp] | 91.84.117.29
  - 🇫🇮 FI [R][grpc] | 31.129.42.239
  - 🇬🇧 GB [R] | 144.31.87.16
  - 🇬🇧 GB [R] | 95.85.224.51
  - 🇫🇮 FI [R][xhttp] | 2.27.42.180
  - 🇳🇱 NL [R] | 46.243.232.122
  - 🇳🇱 NL [R] | wl-1.myfreedom.rest
  - 🇰🇿 KZ [R] | 5.180.40.9
  - 🇰🇿 KZ [R] | 5.180.42.85
  - 🇰🇿 KZ [R] | kz2.techdatacloud.org
  - 🇩🇪 DE [ws] | 84.201.128.112
  - 🇩🇪 DE [ws] | 158.160.196.224
  - 🇫🇷 FR  | fr186.mechvpn.online
  - 🇩🇪 DE [ws] | 185.178.208.176
- name: 🎯 Direct
  type: select
  proxies:
  - DIRECT
  - 🌍 Proxy
rules:
- MATCH,🌍 Proxy
