mode: rule
mixed-port: 7890
allow-lan: true
log-level: info
ipv6: false
tun:
  enable: false
  stack: gvisor
  auto-route: false
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  - 9.9.9.9
  fallback:
  - tls://8.8.8.8
  - tls://1.1.1.1
proxies:
- name: 🇩🇪 DE [R] | 95.163.209.42
  type: vless
  server: 95.163.209.42
  port: 443
  uuid: 8d7032fa-47e2-40b9-86ee-0072b23feff8
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: USzFIqCCFTRAzEJo8Npt_Ds-uRK_FnlvRsR-Iv88_AE
    short-id: a1
  servername: vk.com
  flow: xtls-rprx-vision
  client-fingerprint: firefox
- name: 🇰🇿 KZ [R] | raff-vpn-kz-server1.ru
  type: vless
  server: raff-vpn-kz-server1.ru
  port: 443
  uuid: 6fdfdb73-51b0-4a14-89a5-c9355a0e0397
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: vCxfuNNmogA1DlPkjvmKb7_hSgXqe4MboPfi2s1JZG0
    short-id: b318242471ba4f5b
  servername: google.com
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇩🇪 DE [R] | vkw.t817smgn6zs.ru
  type: vless
  server: vkw.t817smgn6zs.ru
  port: 443
  uuid: 8d7032fa-47e2-40b9-86ee-0072b23feff8
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: USzFIqCCFTRAzEJo8Npt_Ds-uRK_FnlvRsR-Iv88_AE
    short-id: a1
  servername: vk.com
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇵🇱 PL [R][xhttp] | 85.158.109.113
  type: vless
  server: 85.158.109.113
  port: 443
  uuid: 8553ae90-2a81-493a-b050-8ee79c8dbe4c
  udp: true
  skip-cert-verify: true
  network: xhttp
  encryption: none
  tls: true
  reality-opts:
    public-key: ice5ApDYceTGVoxODC51F4RVW0HBoykvMpgL4_qLABw
    short-id: aabbccdd
  servername: www.kinopoisk.ru
  client-fingerprint: firefox
- name: 🇷🇴 RO [R] | 195.74.93.254
  type: vless
  server: 195.74.93.254
  port: 443
  uuid: 146eb6cf-a99c-4022-85ca-022cf81502dc
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 7ReQIe2kMtP4rCrptgH5glkOM-JGcSAPzHNxOED-Z0s
    short-id: 247fd6dab1a34a48
  servername: web.max.ru
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇳🇱 NL [R] | 144.31.30.69
  type: vless
  server: 144.31.30.69
  port: 443
  uuid: f90cc83a-97ce-446d-8f80-30d3eef3351c
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc
    short-id: 6ba85179e30d4fc2
  servername: eh.vk.com
  flow: xtls-rprx-vision
- name: 🇰🇿 KZ [R] | 38.180.39.171
  type: vless
  server: 38.180.39.171
  port: 443
  uuid: 158d03db-e5d7-4540-a31c-b2daa7aa4964
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 7ReQIe2kMtP4rCrptgH5glkOM-JGcSAPzHNxOED-Z0s
    short-id: 247fd6dab1a34a48
  servername: web.max.ru
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇩🇪 DE [R] | 45.13.226.97
  type: vless
  server: 45.13.226.97
  port: 443
  uuid: e0e576ae-2428-4928-a280-2d3b96daf30d
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 3zq_fR7PzSDc9NBQiECTiUISD1rhvsXSMgd_ZIcqvWY
    short-id: ec42626e
  servername: www.avito.ru
- name: 🇳🇱 NL [R] | 194.127.179.220
  type: vless
  server: 194.127.179.220
  port: 443
  uuid: eedcee2e-7517-4162-852d-b21b864b8e3f
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 7ReQIe2kMtP4rCrptgH5glkOM-JGcSAPzHNxOED-Z0s
    short-id: 247fd6dab1a34a48
  servername: web.max.ru
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇩🇪 DE [R] | nodede2.vdkvpn.ru
  type: vless
  server: nodede2.vdkvpn.ru
  port: 443
  uuid: 9b7f9174-42f1-4b0f-8a4a-c3fd7636fc5e
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: u8MN57FhcYnpahcrByDmBNZ9_ruw9C1065QIwpZSZkk
  servername: ya.ru
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇲🇩 MD [R] | md.riotvpn.eu
  type: vless
  server: md.riotvpn.eu
  port: 443
  uuid: c470171c-2951-4806-988d-61d4d811486d
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 8h8t5eBWL9oERK7xWHQLFJE5j6sZdgNDQAs3EGnNbho
    short-id: b76dcf9e1183fe1b
  servername: avatars.mds.yandex.net
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇫🇮 FI [R] | 62.60.228.89
  type: vless
  server: 62.60.228.89
  port: 443
  uuid: 2ea1a3c8-2581-4ead-8291-43fee2f8be3d
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: ydoxmw5pH_JPRTbjeNKnsF-MfVybjnAYLnhwRj3n3yE
    short-id: cf2d
  servername: api.ok.ru
  client-fingerprint: qq
- name: 🇰🇿 KZ [R] | vpnv1.aspidnet.xyz
  type: vless
  server: vpnv1.aspidnet.xyz
  port: 443
  uuid: 158d03db-e5d7-4540-a31c-b2daa7aa4964
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 7ReQIe2kMtP4rCrptgH5glkOM-JGcSAPzHNxOED-Z0s
    short-id: 247fd6dab1a34a48
  servername: web.max.ru
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇷🇴 RO [R] | 195.74.93.254 (2)
  type: vless
  server: 195.74.93.254
  port: 443
  uuid: db2b7549-a616-4d83-a4bf-51eda70ff82c
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 7ReQIe2kMtP4rCrptgH5glkOM-JGcSAPzHNxOED-Z0s
    short-id: 247fd6dab1a34a48
  servername: web.max.ru
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇷🇴 RO [R] | 195.74.93.254 (3)
  type: vless
  server: 195.74.93.254
  port: 443
  uuid: 451ccfb4-4d9f-4d16-a748-48862ff46b86
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 7ReQIe2kMtP4rCrptgH5glkOM-JGcSAPzHNxOED-Z0s
    short-id: 247fd6dab1a34a48
  servername: web.max.ru
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇳🇱 NL [R] | 194.127.179.220 (2)
  type: vless
  server: 194.127.179.220
  port: 443
  uuid: 29f2e850-1551-48ba-9d68-1fb303d3ab6e
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 7ReQIe2kMtP4rCrptgH5glkOM-JGcSAPzHNxOED-Z0s
    short-id: 247fd6dab1a34a48
  servername: web.max.ru
  flow: xtls-rprx-vision
  client-fingerprint: chrome
- name: 🇳🇱 NL [R] | lc2nodenl.vdkvpn.ru
  type: vless
  server: lc2nodenl.vdkvpn.ru
  port: 443
  uuid: 9b7f9174-42f1-4b0f-8a4a-c3fd7636fc5e
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: u8MN57FhcYnpahcrByDmBNZ9_ruw9C1065QIwpZSZkk
  servername: ya.ru
  flow: xtls-rprx-vision
  client-fingerprint: qq
- name: 🇷🇴 RO [R] | 195.74.93.254 (4)
  type: vless
  server: 195.74.93.254
  port: 443
  uuid: eedcee2e-7517-4162-852d-b21b864b8e3f
  udp: true
  skip-cert-verify: true
  network: tcp
  encryption: none
  tls: true
  reality-opts:
    public-key: 7ReQIe2kMtP4rCrptgH5glkOM-JGcSAPzHNxOED-Z0s
    short-id: 247fd6dab1a34a48
  servername: web.max.ru
  flow: xtls-rprx-vision
  client-fingerprint: chrome
proxy-groups:
- name: 🚀 Auto
  type: url-test
  proxies:
  - 🇩🇪 DE [R] | 95.163.209.42
  - 🇰🇿 KZ [R] | raff-vpn-kz-server1.ru
  - 🇩🇪 DE [R] | vkw.t817smgn6zs.ru
  - 🇵🇱 PL [R][xhttp] | 85.158.109.113
  - 🇷🇴 RO [R] | 195.74.93.254
  - 🇳🇱 NL [R] | 144.31.30.69
  - 🇰🇿 KZ [R] | 38.180.39.171
  - 🇩🇪 DE [R] | 45.13.226.97
  - 🇳🇱 NL [R] | 194.127.179.220
  - 🇩🇪 DE [R] | nodede2.vdkvpn.ru
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
- name: 🌍 Proxy
  type: select
  proxies:
  - 🚀 Auto
  - 🇩🇪 DE [R] | 95.163.209.42
  - 🇰🇿 KZ [R] | raff-vpn-kz-server1.ru
  - 🇩🇪 DE [R] | vkw.t817smgn6zs.ru
  - 🇵🇱 PL [R][xhttp] | 85.158.109.113
  - 🇷🇴 RO [R] | 195.74.93.254
  - 🇳🇱 NL [R] | 144.31.30.69
  - 🇰🇿 KZ [R] | 38.180.39.171
  - 🇩🇪 DE [R] | 45.13.226.97
  - 🇳🇱 NL [R] | 194.127.179.220
  - 🇩🇪 DE [R] | nodede2.vdkvpn.ru
  - 🇲🇩 MD [R] | md.riotvpn.eu
  - 🇫🇮 FI [R] | 62.60.228.89
  - 🇰🇿 KZ [R] | vpnv1.aspidnet.xyz
  - 🇷🇴 RO [R] | 195.74.93.254 (2)
  - 🇷🇴 RO [R] | 195.74.93.254 (3)
  - 🇳🇱 NL [R] | 194.127.179.220 (2)
  - 🇳🇱 NL [R] | lc2nodenl.vdkvpn.ru
  - 🇷🇴 RO [R] | 195.74.93.254 (4)
- name: 🎯 Direct
  type: select
  proxies:
  - DIRECT
  - 🌍 Proxy
rules:
- MATCH,🌍 Proxy
