name: Check VLESS Servers

on:
  schedule:
    - cron: "*/9 * * * *"  # каждые 9 минут
  workflow_dispatch:       # можно запускать вручную

jobs:
  check-vless:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Check VLESS servers
        run: |
          python - <<'EOF'
          import os
          import socket
          import urllib.request

          url = 'https://github.com/AvenCores/goida-vpn-configs/raw/refs/heads/main/githubmirror/26.txt'
          content = urllib.request.urlopen(url).read().decode()
          servers = [line.strip() for line in content.splitlines() if line.strip() and line.startswith('vless://')]

          alive = {}  # страна -> server
          for server in servers:
              try:
                  host_port = server.split('//')[1].split('@')[1].split(':')
                  host, port = host_port[0], int(host_port[1])

                  sock = socket.create_connection((host, port), timeout=3)
                  sock.close()

                  country = server.split('#')[-1] if '#' in server else 'unknown'

                  if country not in alive:
                      alive[country] = server

              except Exception:
                  continue

          os.makedirs('githubmirror', exist_ok=True)
          with open('githubmirror/26_alive.txt', 'w') as f:
              f.write('\n'.join(alive.values()))

          print(f"Alive servers: {len(alive)}")
          EOF

      - name: Commit and push alive servers
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add githubmirror/26_alive.txt
          git diff --cached --quiet || git commit -m "Update alive VLESS servers"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
