# Обновлено: 2026-06-19 02:12 UTC
# Всего в источнике: 69
# Живых серверов: 68
# Источник: 26_proxy_subscription_raw.txt
proxies:
- name: 🇺🇸 US | 87.228.101.57
  type: vless
  server: 87.228.101.57
  port: 443
  uuid: 1b3e889d-2442-42b8-81ff-0247612d1f9a
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: rutube.ru
- name: 🇺🇸 US | 87.228.101.211
  type: vless
  server: 87.228.101.211
  port: 443
  uuid: 1b3e889d-2442-42b8-81ff-0247612d1f9a
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: m.vk.com
- name: 🇺🇸 US | 85.239.34.189
  type: vless
  server: 85.239.34.189
  port: 443
  uuid: 4c0e1fb5-08a6-4809-8723-9721f1b1990b
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: rutube.ru
- name: 🇩🇪 DE | 51.250.47.193
  type: vless
  server: 51.250.47.193
  port: 443
  uuid: 5bb2a329-0038-42ae-8618-438cc96085c8
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ads.x5.ru
- name: 🇩🇪 DE | 51.250.4.238
  type: vless
  server: 51.250.4.238
  port: 443
  uuid: 5bb2a329-0038-42ae-8618-438cc96085c8
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: www.vk.com
- name: 🇩🇪 DE | 51.250.47.193 (2)
  type: vless
  server: 51.250.47.193
  port: 443
  uuid: 5bb2a329-0038-42ae-8618-438cc96085c8
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: smartcaptcha.yandexcloud.net
- name: 🇩🇪 DE | 51.250.70.186
  type: vless
  server: 51.250.70.186
  port: 443
  uuid: 849bab03-e8fb-4185-a0ba-cd49d2b160f6
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: yandex.ru
- name: 🇩🇪 DE | 185.229.9.8
  type: vless
  server: 185.229.9.8
  port: 443
  uuid: 849bab03-e8fb-4185-a0ba-cd49d2b160f6
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ads.x5.ru
- name: 🇩🇪 DE | 51.250.70.186 (2)
  type: vless
  server: 51.250.70.186
  port: 443
  uuid: 849bab03-e8fb-4185-a0ba-cd49d2b160f6
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: max.ru
- name: 🇩🇪 DE | 51.250.4.238 (2)
  type: vless
  server: 51.250.4.238
  port: 443
  uuid: 5bb2a329-0038-42ae-8618-438cc96085c8
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: yandex.ru
- name: 🇩🇪 DE | 51.250.47.193 (3)
  type: vless
  server: 51.250.47.193
  port: 443
  uuid: 5bb2a329-0038-42ae-8618-438cc96085c8
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: api-maps.yandex.ru
- name: 🇩🇪 DE | 51.250.47.193 (4)
  type: vless
  server: 51.250.47.193
  port: 443
  uuid: bc7432ed-2b15-44eb-a903-6f91f9d150f0
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: api-maps.yandex.ru
- name: 🇩🇪 DE | 51.250.4.238 (3)
  type: vless
  server: 51.250.4.238
  port: 443
  uuid: 5bb2a329-0038-42ae-8618-438cc96085c8
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: max.ru
- name: 🇩🇪 DE | 51.250.47.193 (5)
  type: vless
  server: 51.250.47.193
  port: 443
  uuid: bc7432ed-2b15-44eb-a903-6f91f9d150f0
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: smartcaptcha.yandexcloud.net
- name: 🇩🇪 DE | 217.16.27.113
  type: vless
  server: 217.16.27.113
  port: 443
  uuid: f080e64a-ff64-4bab-9818-86a73cd86204
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: eh.vk.com
- name: 🇺🇸 US | 178.154.214.111
  type: vless
  server: 178.154.214.111
  port: 443
  uuid: 1b3e889d-2442-42b8-81ff-0247612d1f9a
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: smartcaptcha.yandexcloud.net
- name: 🇩🇪 DE | 51.250.98.184
  type: vless
  server: 51.250.98.184
  port: 443
  uuid: 849bab03-e8fb-4185-a0ba-cd49d2b160f6
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: yandex.ru
- name: 🇩🇪 DE | 51.250.98.184 (2)
  type: vless
  server: 51.250.98.184
  port: 443
  uuid: 849bab03-e8fb-4185-a0ba-cd49d2b160f6
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: www.vk.com
- name: 🇩🇪 DE | 217.16.27.113 (2)
  type: vless
  server: 217.16.27.113
  port: 443
  uuid: f080e64a-ff64-4bab-9818-86a73cd86204
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ads.x5.ru
- name: 🇩🇪 DE | 51.250.47.193 (6)
  type: vless
  server: 51.250.47.193
  port: 443
  uuid: bc7432ed-2b15-44eb-a903-6f91f9d150f0
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ads.x5.ru
- name: 🇩🇪 DE | 51.250.4.238 (4)
  type: vless
  server: 51.250.4.238
  port: 443
  uuid: bc7432ed-2b15-44eb-a903-6f91f9d150f0
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: yandex.ru
- name: 🇺🇸 US | 178.154.214.111 (2)
  type: vless
  server: 178.154.214.111
  port: 443
  uuid: 1b3e889d-2442-42b8-81ff-0247612d1f9a
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ads.x5.ru
- name: 🇩🇪 DE | 158.160.17.171
  type: vless
  server: 158.160.17.171
  port: 443
  uuid: 5bb2a329-0038-42ae-8618-438cc96085c8
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: api-maps.yandex.ru
- name: 🇩🇪 DE | 51.250.98.184 (3)
  type: vless
  server: 51.250.98.184
  port: 443
  uuid: 849bab03-e8fb-4185-a0ba-cd49d2b160f6
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: max.ru
- name: 🇩🇪 DE | 51.250.4.238 (5)
  type: vless
  server: 51.250.4.238
  port: 443
  uuid: bc7432ed-2b15-44eb-a903-6f91f9d150f0
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: www.vk.com
- name: 🇺🇸 US | 178.154.214.111 (3)
  type: vless
  server: 178.154.214.111
  port: 443
  uuid: 1b3e889d-2442-42b8-81ff-0247612d1f9a
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: api-maps.yandex.ru
- name: 🇨🇭 CH | 51.250.47.219
  type: vless
  server: 51.250.47.219
  port: 443
  uuid: 2d31f11f-a05a-4625-b4ec-05a75d57de3a
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: yandex.ru
- name: 🇨🇭 CH | 185.130.114.211
  type: vless
  server: 185.130.114.211
  port: 443
  uuid: 2d31f11f-a05a-4625-b4ec-05a75d57de3a
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: yandex.ru
- name: 🇩🇪 DE | 51.250.70.186 (3)
  type: vless
  server: 51.250.70.186
  port: 443
  uuid: 849bab03-e8fb-4185-a0ba-cd49d2b160f6
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: www.vk.com
- name: 🇩🇪 DE | 51.250.30.235
  type: vless
  server: 51.250.30.235
  port: 443
  uuid: 849bab03-e8fb-4185-a0ba-cd49d2b160f6
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: www.vk.com
- name: 🇩🇪 DE | 84.201.153.33
  type: vless
  server: 84.201.153.33
  port: 443
  uuid: 5bb2a329-0038-42ae-8618-438cc96085c8
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: smartcaptcha.yandexcloud.net
- name: 🇩🇪 DE | 158.160.17.171 (2)
  type: vless
  server: 158.160.17.171
  port: 443
  uuid: bc7432ed-2b15-44eb-a903-6f91f9d150f0
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: smartcaptcha.yandexcloud.net
- name: 🇺🇸 US | 84.201.180.178
  type: vless
  server: 84.201.180.178
  port: 443
  uuid: 1b3e889d-2442-42b8-81ff-0247612d1f9a
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: smartcaptcha.yandexcloud.net
- name: 🇩🇪 DE | 51.250.4.238 (6)
  type: vless
  server: 51.250.4.238
  port: 443
  uuid: bc7432ed-2b15-44eb-a903-6f91f9d150f0
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: max.ru
- name: 🇩🇪 DE | 84.201.153.33 (2)
  type: vless
  server: 84.201.153.33
  port: 443
  uuid: 5bb2a329-0038-42ae-8618-438cc96085c8
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: api-maps.yandex.ru
- name: 🇩🇪 DE | 84.201.164.23
  type: vless
  server: 84.201.164.23
  port: 443
  uuid: 849bab03-e8fb-4185-a0ba-cd49d2b160f6
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ads.x5.ru
- name: 🇩🇪 DE | 217.16.27.113 (3)
  type: vless
  server: 217.16.27.113
  port: 443
  uuid: f080e64a-ff64-4bab-9818-86a73cd86204
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: max.ru
- name: 🇩🇪 DE | 158.160.17.171 (3)
  type: vless
  server: 158.160.17.171
  port: 443
  uuid: bc7432ed-2b15-44eb-a903-6f91f9d150f0
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ads.x5.ru
- name: 🇩🇪 DE | 51.250.30.235 (2)
  type: vless
  server: 51.250.30.235
  port: 443
  uuid: 849bab03-e8fb-4185-a0ba-cd49d2b160f6
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: yandex.ru
- name: 🇩🇪 DE | 84.201.153.33 (3)
  type: vless
  server: 84.201.153.33
  port: 443
  uuid: bc7432ed-2b15-44eb-a903-6f91f9d150f0
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: api-maps.yandex.ru
- name: 🇩🇪 DE | 84.201.164.23 (2)
  type: vless
  server: 84.201.164.23
  port: 443
  uuid: 849bab03-e8fb-4185-a0ba-cd49d2b160f6
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: smartcaptcha.yandexcloud.net
- name: 🇺🇸 US | 51.250.40.74
  type: vless
  server: 51.250.40.74
  port: 443
  uuid: 1b3e889d-2442-42b8-81ff-0247612d1f9a
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: smartcaptcha.yandexcloud.net
- name: 🇩🇪 DE | 84.201.164.23 (3)
  type: vless
  server: 84.201.164.23
  port: 443
  uuid: 849bab03-e8fb-4185-a0ba-cd49d2b160f6
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: api-maps.yandex.ru
- name: 🇩🇪 DE | 84.201.153.33 (4)
  type: vless
  server: 84.201.153.33
  port: 443
  uuid: bc7432ed-2b15-44eb-a903-6f91f9d150f0
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: smartcaptcha.yandexcloud.net
- name: 🇩🇪 DE | 87.236.22.165
  type: vless
  server: 87.236.22.165
  port: 443
  uuid: b1a31ff7-4a4c-45ed-b4db-1c46a78f961c
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ads.x5.ru
  network: grpc
  grpc-opts:
    grpc-service-name: ''
- name: 🇩🇪 DE | 51.250.30.235 (3)
  type: vless
  server: 51.250.30.235
  port: 443
  uuid: 849bab03-e8fb-4185-a0ba-cd49d2b160f6
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: max.ru
- name: 🇩🇪 DE | 158.160.17.171 (4)
  type: vless
  server: 158.160.17.171
  port: 443
  uuid: bc7432ed-2b15-44eb-a903-6f91f9d150f0
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: api-maps.yandex.ru
- name: 🇩🇪 DE | 84.201.153.33 (5)
  type: vless
  server: 84.201.153.33
  port: 443
  uuid: bc7432ed-2b15-44eb-a903-6f91f9d150f0
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ads.x5.ru
- name: 🇨🇭 CH | 185.130.115.132
  type: vless
  server: 185.130.115.132
  port: 443
  uuid: 2d31f11f-a05a-4625-b4ec-05a75d57de3a
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: yandex.ru
- name: 🇳🇱 NL | 146.19.254.109
  type: vless
  server: 146.19.254.109
  port: 443
  uuid: 68001b7e-e48a-5a02-8243-c1a2a37b66b7
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ya.ru
  network: grpc
  grpc-opts:
    grpc-service-name: ''
- name: 🇳🇱 NL | 144.31.30.69
  type: vless
  server: 144.31.30.69
  port: 443
  uuid: f90cc83a-97ce-446d-8f80-30d3eef3351c
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: eh.vk.com
- name: 🇳🇱 NL | 146.19.254.109 (2)
  type: vless
  server: 146.19.254.109
  port: 443
  uuid: JetVPN_979711
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ya.ru
  network: grpc
  grpc-opts:
    grpc-service-name: ''
- name: 🇷🇴 RO | 195.74.93.254
  type: vless
  server: 195.74.93.254
  port: 443
  uuid: 146eb6cf-a99c-4022-85ca-022cf81502dc
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: web.max.ru
- name: 🇺🇸 US | 87.228.101.57 (2)
  type: vless
  server: 87.228.101.57
  port: 443
  uuid: 1b3e889d-2442-42b8-81ff-0247612d1f9a
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: api-maps.yandex.ru
- name: 🇺🇸 US | 87.228.101.211 (2)
  type: vless
  server: 87.228.101.211
  port: 443
  uuid: 1b3e889d-2442-42b8-81ff-0247612d1f9a
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: 5post-gate.x5.ru
- name: 🇫🇮 FI | 46.62.129.198
  type: vless
  server: 46.62.129.198
  port: 443
  uuid: 1b9e301d-cecd-4eb1-8b36-eef811c2696d
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: sberbank.ru
- name: 🇺🇸 US | 51.250.40.74 (2)
  type: vless
  server: 51.250.40.74
  port: 443
  uuid: 1b3e889d-2442-42b8-81ff-0247612d1f9a
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ads.x5.ru
- name: 🇫🇮 FI | 62.60.255.11
  type: vless
  server: 62.60.255.11
  port: 443
  uuid: ad8a53f2-b109-4873-9156-fc3bcb0d7fe4
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ya.ru
- name: 🇺🇸 US | 158.160.208.250
  type: vless
  server: 158.160.208.250
  port: 443
  uuid: 1b3e889d-2442-42b8-81ff-0247612d1f9a
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: api-maps.yandex.ru
- name: 🇺🇸 US | 158.160.208.250 (2)
  type: vless
  server: 158.160.208.250
  port: 443
  uuid: 1b3e889d-2442-42b8-81ff-0247612d1f9a
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: smartcaptcha.yandexcloud.net
- name: 🇷🇴 RO | 93.114.194.131
  type: vless
  server: 93.114.194.131
  port: 443
  uuid: 146eb6cf-a99c-4022-85ca-022cf81502dc
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: web.max.ru
- name: 🇺🇸 US | 51.250.40.74 (3)
  type: vless
  server: 51.250.40.74
  port: 443
  uuid: 1b3e889d-2442-42b8-81ff-0247612d1f9a
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: api-maps.yandex.ru
- name: 🇸🇪 SE | se1.vitok.cc
  type: vless
  server: se1.vitok.cc
  port: 443
  uuid: 1b9e301d-cecd-4eb1-8b36-eef811c2696d
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: yastatic.net
- name: 🇸🇪 SE | 178.250.242.196
  type: vless
  server: 178.250.242.196
  port: 443
  uuid: aba883e4-c129-438b-900d-7d8b27958002
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ads.x5.ru
  network: grpc
  grpc-opts:
    grpc-service-name: ''
- name: 🇫🇮 FI | fi1.vitok.cc
  type: vless
  server: fi1.vitok.cc
  port: 443
  uuid: 1b9e301d-cecd-4eb1-8b36-eef811c2696d
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: sberbank.ru
- name: 🇰🇿 KZ | 38.180.39.171
  type: vless
  server: 38.180.39.171
  port: 443
  uuid: 158d03db-e5d7-4540-a31c-b2daa7aa4964
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: web.max.ru
- name: 🇫🇮 FI | 217.114.12.187
  type: vless
  server: 217.114.12.187
  port: 443
  uuid: 1281ef13-f1cd-493b-903e-4c2f4ffe1eba
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: dzen.ru
- name: 🇫🇮 FI | 45.141.79.64
  type: vless
  server: 45.141.79.64
  port: 443
  uuid: 1281ef13-f1cd-493b-903e-4c2f4ffe1eba
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: dzen.ru
proxy-groups:
- name: 🚀 Авто-выбор
  type: url-test
  proxies:
  - 🇺🇸 US | 87.228.101.57
  - 🇺🇸 US | 87.228.101.211
  - 🇺🇸 US | 85.239.34.189
  - 🇩🇪 DE | 51.250.47.193
  - 🇩🇪 DE | 51.250.4.238
  - 🇩🇪 DE | 51.250.47.193 (2)
  - 🇩🇪 DE | 51.250.70.186
  - 🇩🇪 DE | 185.229.9.8
  - 🇩🇪 DE | 51.250.70.186 (2)
  - 🇩🇪 DE | 51.250.4.238 (2)
  - 🇩🇪 DE | 51.250.47.193 (3)
  - 🇩🇪 DE | 51.250.47.193 (4)
  - 🇩🇪 DE | 51.250.4.238 (3)
  - 🇩🇪 DE | 51.250.47.193 (5)
  - 🇩🇪 DE | 217.16.27.113
  - 🇺🇸 US | 178.154.214.111
  - 🇩🇪 DE | 51.250.98.184
  - 🇩🇪 DE | 51.250.98.184 (2)
  - 🇩🇪 DE | 217.16.27.113 (2)
  - 🇩🇪 DE | 51.250.47.193 (6)
  - 🇩🇪 DE | 51.250.4.238 (4)
  - 🇺🇸 US | 178.154.214.111 (2)
  - 🇩🇪 DE | 158.160.17.171
  - 🇩🇪 DE | 51.250.98.184 (3)
  - 🇩🇪 DE | 51.250.4.238 (5)
  - 🇺🇸 US | 178.154.214.111 (3)
  - 🇨🇭 CH | 51.250.47.219
  - 🇨🇭 CH | 185.130.114.211
  - 🇩🇪 DE | 51.250.70.186 (3)
  - 🇩🇪 DE | 51.250.30.235
  - 🇩🇪 DE | 84.201.153.33
  - 🇩🇪 DE | 158.160.17.171 (2)
  - 🇺🇸 US | 84.201.180.178
  - 🇩🇪 DE | 51.250.4.238 (6)
  - 🇩🇪 DE | 84.201.153.33 (2)
  - 🇩🇪 DE | 84.201.164.23
  - 🇩🇪 DE | 217.16.27.113 (3)
  - 🇩🇪 DE | 158.160.17.171 (3)
  - 🇩🇪 DE | 51.250.30.235 (2)
  - 🇩🇪 DE | 84.201.153.33 (3)
  - 🇩🇪 DE | 84.201.164.23 (2)
  - 🇺🇸 US | 51.250.40.74
  - 🇩🇪 DE | 84.201.164.23 (3)
  - 🇩🇪 DE | 84.201.153.33 (4)
  - 🇩🇪 DE | 87.236.22.165
  - 🇩🇪 DE | 51.250.30.235 (3)
  - 🇩🇪 DE | 158.160.17.171 (4)
  - 🇩🇪 DE | 84.201.153.33 (5)
  - 🇨🇭 CH | 185.130.115.132
  - 🇳🇱 NL | 146.19.254.109
  - 🇳🇱 NL | 144.31.30.69
  - 🇳🇱 NL | 146.19.254.109 (2)
  - 🇷🇴 RO | 195.74.93.254
  - 🇺🇸 US | 87.228.101.57 (2)
  - 🇺🇸 US | 87.228.101.211 (2)
  - 🇫🇮 FI | 46.62.129.198
  - 🇺🇸 US | 51.250.40.74 (2)
  - 🇫🇮 FI | 62.60.255.11
  - 🇺🇸 US | 158.160.208.250
  - 🇺🇸 US | 158.160.208.250 (2)
  - 🇷🇴 RO | 93.114.194.131
  - 🇺🇸 US | 51.250.40.74 (3)
  - 🇸🇪 SE | se1.vitok.cc
  - 🇸🇪 SE | 178.250.242.196
  - 🇫🇮 FI | fi1.vitok.cc
  - 🇰🇿 KZ | 38.180.39.171
  - 🇫🇮 FI | 217.114.12.187
  - 🇫🇮 FI | 45.141.79.64
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🌍 Прокси
  type: select
  proxies:
  - 🚀 Авто-выбор
  - 🇺🇸 US | 87.228.101.57
  - 🇺🇸 US | 87.228.101.211
  - 🇺🇸 US | 85.239.34.189
  - 🇩🇪 DE | 51.250.47.193
  - 🇩🇪 DE | 51.250.4.238
  - 🇩🇪 DE | 51.250.47.193 (2)
  - 🇩🇪 DE | 51.250.70.186
  - 🇩🇪 DE | 185.229.9.8
  - 🇩🇪 DE | 51.250.70.186 (2)
  - 🇩🇪 DE | 51.250.4.238 (2)
  - 🇩🇪 DE | 51.250.47.193 (3)
  - 🇩🇪 DE | 51.250.47.193 (4)
  - 🇩🇪 DE | 51.250.4.238 (3)
  - 🇩🇪 DE | 51.250.47.193 (5)
  - 🇩🇪 DE | 217.16.27.113
  - 🇺🇸 US | 178.154.214.111
  - 🇩🇪 DE | 51.250.98.184
  - 🇩🇪 DE | 51.250.98.184 (2)
  - 🇩🇪 DE | 217.16.27.113 (2)
  - 🇩🇪 DE | 51.250.47.193 (6)
  - 🇩🇪 DE | 51.250.4.238 (4)
  - 🇺🇸 US | 178.154.214.111 (2)
  - 🇩🇪 DE | 158.160.17.171
  - 🇩🇪 DE | 51.250.98.184 (3)
  - 🇩🇪 DE | 51.250.4.238 (5)
  - 🇺🇸 US | 178.154.214.111 (3)
  - 🇨🇭 CH | 51.250.47.219
  - 🇨🇭 CH | 185.130.114.211
  - 🇩🇪 DE | 51.250.70.186 (3)
  - 🇩🇪 DE | 51.250.30.235
  - 🇩🇪 DE | 84.201.153.33
  - 🇩🇪 DE | 158.160.17.171 (2)
  - 🇺🇸 US | 84.201.180.178
  - 🇩🇪 DE | 51.250.4.238 (6)
  - 🇩🇪 DE | 84.201.153.33 (2)
  - 🇩🇪 DE | 84.201.164.23
  - 🇩🇪 DE | 217.16.27.113 (3)
  - 🇩🇪 DE | 158.160.17.171 (3)
  - 🇩🇪 DE | 51.250.30.235 (2)
  - 🇩🇪 DE | 84.201.153.33 (3)
  - 🇩🇪 DE | 84.201.164.23 (2)
  - 🇺🇸 US | 51.250.40.74
  - 🇩🇪 DE | 84.201.164.23 (3)
  - 🇩🇪 DE | 84.201.153.33 (4)
  - 🇩🇪 DE | 87.236.22.165
  - 🇩🇪 DE | 51.250.30.235 (3)
  - 🇩🇪 DE | 158.160.17.171 (4)
  - 🇩🇪 DE | 84.201.153.33 (5)
  - 🇨🇭 CH | 185.130.115.132
  - 🇳🇱 NL | 146.19.254.109
  - 🇳🇱 NL | 144.31.30.69
  - 🇳🇱 NL | 146.19.254.109 (2)
  - 🇷🇴 RO | 195.74.93.254
  - 🇺🇸 US | 87.228.101.57 (2)
  - 🇺🇸 US | 87.228.101.211 (2)
  - 🇫🇮 FI | 46.62.129.198
  - 🇺🇸 US | 51.250.40.74 (2)
  - 🇫🇮 FI | 62.60.255.11
  - 🇺🇸 US | 158.160.208.250
  - 🇺🇸 US | 158.160.208.250 (2)
  - 🇷🇴 RO | 93.114.194.131
  - 🇺🇸 US | 51.250.40.74 (3)
  - 🇸🇪 SE | se1.vitok.cc
  - 🇸🇪 SE | 178.250.242.196
  - 🇫🇮 FI | fi1.vitok.cc
  - 🇰🇿 KZ | 38.180.39.171
  - 🇫🇮 FI | 217.114.12.187
  - 🇫🇮 FI | 45.141.79.64
rules:
- MATCH,🌍 Прокси
