# Обновлено: 2026-06-13 00:12 UTC
# Всего в источнике: 22
# Живых серверов: 21
# Источник: 26_proxy_subscription_raw.txt
proxies:
- name: 🇳🇱 NL | 194.127.179.220
  type: vless
  server: 194.127.179.220
  port: 443
  uuid: 146eb6cf-a99c-4022-85ca-022cf81502dc
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: web.max.ru
- name: 🇳🇱 NL | 144.31.30.69
  type: vless
  server: 144.31.30.69
  port: 443
  uuid: f90cc83a-97ce-446d-8f80-30d3eef3351c
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: eh.vk.com
- name: 🇷🇴 RO | 195.74.93.254
  type: vless
  server: 195.74.93.254
  port: 443
  uuid: 146eb6cf-a99c-4022-85ca-022cf81502dc
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: web.max.ru
- name: 🇩🇪 DE | 88.210.62.3
  type: vless
  server: 88.210.62.3
  port: 443
  uuid: 75e3f61c-9ade-41b8-840f-39d41d8208c6
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: sun6-21.userapi.com
- name: 🇫🇮 FI | 94.237.115.30
  type: vless
  server: 94.237.115.30
  port: 443
  uuid: a957d0fb-4641-4307-aa38-1f893b1ae987
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: cloudcdn-m9-9.cdn.yandex.net
- name: 🇺🇸 US | 2.26.93.251
  type: vless
  server: 2.26.93.251
  port: 443
  uuid: 8ea0665e-dee3-418c-8822-1f70f350f2db
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: yandex.net
- name: 🇮🇱 IL | 31.76.34.81
  type: vless
  server: 31.76.34.81
  port: 443
  uuid: aa9d833c-254b-4ce0-9bd4-2d535532f5d6
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ya.ru
- name: 🇺🇸 US | 31.76.34.86
  type: vless
  server: 31.76.34.86
  port: 443
  uuid: 08fc840b-e673-4031-aa2f-2663cadf838a
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ya.ru
- name: 🇳🇱 NL | 31.76.34.88
  type: vless
  server: 31.76.34.88
  port: 443
  uuid: c4f21079-3f22-428d-9161-c936ad685775
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ya.ru
- name: 🇸🇬 SG | 31.76.34.85
  type: vless
  server: 31.76.34.85
  port: 443
  uuid: be018243-71b9-4e87-a6d0-db512d31c554
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ya.ru
- name: 🇺🇸 US | 2.26.93.43
  type: vless
  server: 2.26.93.43
  port: 443
  uuid: 8ea0665e-dee3-418c-8822-1f70f350f2db
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: yandex.net
- name: 🇷🇴 RO | 93.114.194.131
  type: vless
  server: 93.114.194.131
  port: 443
  uuid: 146eb6cf-a99c-4022-85ca-022cf81502dc
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: web.max.ru
- name: 🇫🇮 FI | 62.60.255.11
  type: vless
  server: 62.60.255.11
  port: 443
  uuid: ad8a53f2-b109-4873-9156-fc3bcb0d7fe4
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ya.ru
- name: 🇸🇪 SE | 31.76.34.87
  type: vless
  server: 31.76.34.87
  port: 443
  uuid: 9c387b24-56ea-458d-b113-ab750a4c9b7b
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ya.ru
- name: 🇺🇸 US | sw.pink-perfect.ru
  type: vless
  server: sw.pink-perfect.ru
  port: 443
  uuid: 8ea0665e-dee3-418c-8822-1f70f350f2db
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: yandex.net
- name: 🇩🇪 DE | de.pink-perfect.ru
  type: vless
  server: de.pink-perfect.ru
  port: 443
  uuid: 8ea0665e-dee3-418c-8822-1f70f350f2db
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: yandex.net
- name: 🇰🇿 KZ | 38.180.39.171
  type: vless
  server: 38.180.39.171
  port: 443
  uuid: 158d03db-e5d7-4540-a31c-b2daa7aa4964
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: web.max.ru
- name: 🇦🇹 AT | as.pink-perfect.ru
  type: vless
  server: as.pink-perfect.ru
  port: 443
  uuid: 8ea0665e-dee3-418c-8822-1f70f350f2db
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: as.pink-perfect.ru
- name: 🇲🇩 MD | md.riotvpn.eu
  type: vless
  server: md.riotvpn.eu
  port: 443
  uuid: c470171c-2951-4806-988d-61d4d811486d
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: avatars.mds.yandex.net
- name: 🇰🇿 KZ | vpnv1.aspidnet.xyz
  type: vless
  server: vpnv1.aspidnet.xyz
  port: 443
  uuid: 158d03db-e5d7-4540-a31c-b2daa7aa4964
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: web.max.ru
- name: 🇳🇱 NL | 193.233.82.126
  type: vless
  server: 193.233.82.126
  port: 443
  uuid: 3ef170be-05d0-479c-9753-aa2f860964ea
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: cloudflare.com
proxy-groups:
- name: 🚀 Авто-выбор
  type: url-test
  proxies:
  - 🇳🇱 NL | 194.127.179.220
  - 🇳🇱 NL | 144.31.30.69
  - 🇷🇴 RO | 195.74.93.254
  - 🇩🇪 DE | 88.210.62.3
  - 🇫🇮 FI | 94.237.115.30
  - 🇺🇸 US | 2.26.93.251
  - 🇮🇱 IL | 31.76.34.81
  - 🇺🇸 US | 31.76.34.86
  - 🇳🇱 NL | 31.76.34.88
  - 🇸🇬 SG | 31.76.34.85
  - 🇺🇸 US | 2.26.93.43
  - 🇷🇴 RO | 93.114.194.131
  - 🇫🇮 FI | 62.60.255.11
  - 🇸🇪 SE | 31.76.34.87
  - 🇺🇸 US | sw.pink-perfect.ru
  - 🇩🇪 DE | de.pink-perfect.ru
  - 🇰🇿 KZ | 38.180.39.171
  - 🇦🇹 AT | as.pink-perfect.ru
  - 🇲🇩 MD | md.riotvpn.eu
  - 🇰🇿 KZ | vpnv1.aspidnet.xyz
  - 🇳🇱 NL | 193.233.82.126
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🌍 Прокси
  type: select
  proxies:
  - 🚀 Авто-выбор
  - 🇳🇱 NL | 194.127.179.220
  - 🇳🇱 NL | 144.31.30.69
  - 🇷🇴 RO | 195.74.93.254
  - 🇩🇪 DE | 88.210.62.3
  - 🇫🇮 FI | 94.237.115.30
  - 🇺🇸 US | 2.26.93.251
  - 🇮🇱 IL | 31.76.34.81
  - 🇺🇸 US | 31.76.34.86
  - 🇳🇱 NL | 31.76.34.88
  - 🇸🇬 SG | 31.76.34.85
  - 🇺🇸 US | 2.26.93.43
  - 🇷🇴 RO | 93.114.194.131
  - 🇫🇮 FI | 62.60.255.11
  - 🇸🇪 SE | 31.76.34.87
  - 🇺🇸 US | sw.pink-perfect.ru
  - 🇩🇪 DE | de.pink-perfect.ru
  - 🇰🇿 KZ | 38.180.39.171
  - 🇦🇹 AT | as.pink-perfect.ru
  - 🇲🇩 MD | md.riotvpn.eu
  - 🇰🇿 KZ | vpnv1.aspidnet.xyz
  - 🇳🇱 NL | 193.233.82.126
rules:
- MATCH,🌍 Прокси
