# Обновлено: 2026-06-20 16:11 UTC
# Всего в источнике: 33
# Живых серверов: 33
# Источник: 26_proxy_subscription_raw.txt
proxies:
- name: 🇺🇸 US [R][grpc] | 45.90.12.239
  type: vless
  server: 45.90.12.239
  port: 443
  uuid: ad546c31-82ec-4558-ac49-5ce28883b59f
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: apple.com
  network: grpc
  grpc-opts:
    grpc-service-name: xyz
- name: 🇳🇱 NL [R] | 195.184.247.178
  type: vless
  server: 195.184.247.178
  port: 443
  uuid: ea0a2f27-7e22-4337-820b-6703eca2d7b4
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: google.com
- name: 🇳🇱 NL [R] | 194.127.179.220
  type: vless
  server: 194.127.179.220
  port: 443
  uuid: 29f2e850-1551-48ba-9d68-1fb303d3ab6e
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: web.max.ru
- name: 🇳🇱 NL [R] | 194.127.179.220 (2)
  type: vless
  server: 194.127.179.220
  port: 443
  uuid: 146eb6cf-a99c-4022-85ca-022cf81502dc
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: web.max.ru
- name: 🇳🇱 NL [R] | 144.31.30.69
  type: vless
  server: 144.31.30.69
  port: 443
  uuid: f90cc83a-97ce-446d-8f80-30d3eef3351c
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: eh.vk.com
- name: 🇷🇴 RO [R] | 195.74.93.254
  type: vless
  server: 195.74.93.254
  port: 443
  uuid: 146eb6cf-a99c-4022-85ca-022cf81502dc
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: web.max.ru
- name: 🇷🇴 RO [R] | 195.74.93.254 (2)
  type: vless
  server: 195.74.93.254
  port: 443
  uuid: db2b7549-a616-4d83-a4bf-51eda70ff82c
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: web.max.ru
- name: 🇷🇴 RO [R] | 195.74.93.254 (3)
  type: vless
  server: 195.74.93.254
  port: 443
  uuid: 809bce92-45a0-4fe3-af1d-79d1c8422606
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: web.max.ru
- name: 🇳🇱 NL [R] | 195.184.247.170
  type: vless
  server: 195.184.247.170
  port: 443
  uuid: ea0a2f27-7e22-4337-820b-6703eca2d7b4
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: google.com
- name: 🇷🇴 RO [R] | 195.74.93.254 (4)
  type: vless
  server: 195.74.93.254
  port: 443
  uuid: eedcee2e-7517-4162-852d-b21b864b8e3f
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: web.max.ru
- name: 🇷🇴 RO [R] | 195.74.93.254 (5)
  type: vless
  server: 195.74.93.254
  port: 443
  uuid: 451ccfb4-4d9f-4d16-a748-48862ff46b86
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: web.max.ru
- name: 🇸🇪 SE [R][grpc] | 185.58.115.149
  type: vless
  server: 185.58.115.149
  port: 443
  uuid: ed3e860f-c97d-45be-a56b-47b77da11059
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: google.com
  network: grpc
  grpc-opts:
    grpc-service-name: data-sync
- name: 🇸🇪 SE [R] | 70.34.194.57
  type: vless
  server: 70.34.194.57
  port: 443
  uuid: 1b9e301d-cecd-4eb1-8b36-eef811c2696d
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: yastatic.net
- name: 🇫🇮 FI [R] | 62.60.255.11
  type: vless
  server: 62.60.255.11
  port: 443
  uuid: ad8a53f2-b109-4873-9156-fc3bcb0d7fe4
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ya.ru
- name: 🇵🇱 PL [R][xhttp] | 85.158.109.113
  type: vless
  server: 85.158.109.113
  port: 443
  uuid: 8553ae90-2a81-493a-b050-8ee79c8dbe4c
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: www.kinopoisk.ru
- name: 🇵🇱 PL [R][grpc] | 138.124.20.201
  type: vless
  server: 138.124.20.201
  port: 443
  uuid: 4169ca30-91e6-4a55-9174-85c08ec55626
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: google.com
  network: grpc
  grpc-opts:
    grpc-service-name: grpc
- name: 🇬🇧 GB [R] | 144.31.217.99
  type: vless
  server: 144.31.217.99
  port: 443
  uuid: 749a5df1-2d12-45cf-80f3-f85ea6b2e405
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: google.com
- name: 🇬🇧 GB [R] | 150.241.101.222
  type: vless
  server: 150.241.101.222
  port: 443
  uuid: 749a5df1-2d12-45cf-80f3-f85ea6b2e405
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: google.com
- name: 🇱🇻 LV [R] | 185.145.245.113
  type: vless
  server: 185.145.245.113
  port: 443
  uuid: 98f268b5-77a7-4185-a002-a6c835d36109
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: dev.max.ru
- name: 🇸🇪 SE [R][grpc] | sw-3.coinbridge.nl
  type: vless
  server: sw-3.coinbridge.nl
  port: 443
  uuid: ed3e860f-c97d-45be-a56b-47b77da11059
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: google.com
  network: grpc
  grpc-opts:
    grpc-service-name: data-sync
- name: 🇫🇮 FI [R] | 150.241.71.35
  type: vless
  server: 150.241.71.35
  port: 443
  uuid: 4f51ca84-43ea-4087-b8a2-938e0ccbe27a
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: google.com
- name: 🇬🇧 GB [R] | 2.26.88.109
  type: vless
  server: 2.26.88.109
  port: 443
  uuid: 749a5df1-2d12-45cf-80f3-f85ea6b2e405
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: google.com
- name: 🇵🇱 PL [R] | pl1.vitok.cc
  type: vless
  server: pl1.vitok.cc
  port: 443
  uuid: 1b9e301d-cecd-4eb1-8b36-eef811c2696d
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: ozon.ru
- name: 🇵🇱 PL [R] | 144.31.1.83
  type: vless
  server: 144.31.1.83
  port: 443
  uuid: 281da500-0018-4991-b5d7-feb4ab627f3a
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: sun9-35.userapi.com
- name: 🇷🇴 RO [R] | 93.114.194.131
  type: vless
  server: 93.114.194.131
  port: 443
  uuid: 146eb6cf-a99c-4022-85ca-022cf81502dc
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: web.max.ru
- name: 🇵🇱 PL [R][xhttp] | pol6.odavpn.online
  type: vless
  server: pol6.odavpn.online
  port: 443
  uuid: 8553ae90-2a81-493a-b050-8ee79c8dbe4c
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: www.kinopoisk.ru
- name: 🇸🇪 SE [R] | se1.vitok.cc
  type: vless
  server: se1.vitok.cc
  port: 443
  uuid: 1b9e301d-cecd-4eb1-8b36-eef811c2696d
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: yastatic.net
- name: 🇩🇪 DE [R] | 103.109.234.138
  type: vless
  server: 103.109.234.138
  port: 443
  uuid: ea0a2f27-7e22-4337-820b-6703eca2d7b4
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: google.com
- name: 🇰🇿 KZ [R] | 38.180.39.171
  type: vless
  server: 38.180.39.171
  port: 443
  uuid: 158d03db-e5d7-4540-a31c-b2daa7aa4964
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: web.max.ru
- name: 🇰🇿 KZ [R] | vpnv1.aspidnet.xyz
  type: vless
  server: vpnv1.aspidnet.xyz
  port: 443
  uuid: 158d03db-e5d7-4540-a31c-b2daa7aa4964
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: web.max.ru
- name: 🇲🇩 MD [R] | md.riotvpn.eu
  type: vless
  server: md.riotvpn.eu
  port: 443
  uuid: 84b504e4-a97f-40ab-93c3-a03a5f0ff36c
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: avatars.mds.yandex.net
- name: 🇲🇩 MD [R] | md.riotvpn.eu (2)
  type: vless
  server: md.riotvpn.eu
  port: 443
  uuid: c470171c-2951-4806-988d-61d4d811486d
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: avatars.mds.yandex.net
- name: 🇰🇿 KZ [R] | raff-vpn-kz-server1.ru
  type: vless
  server: raff-vpn-kz-server1.ru
  port: 443
  uuid: 6fdfdb73-51b0-4a14-89a5-c9355a0e0397
  udp: true
  skip-cert-verify: true
  encryption: none
  sni: google.com
proxy-groups:
- name: 🚀 Авто-выбор
  type: url-test
  proxies:
  - 🇺🇸 US [R][grpc] | 45.90.12.239
  - 🇳🇱 NL [R] | 195.184.247.178
  - 🇳🇱 NL [R] | 194.127.179.220
  - 🇳🇱 NL [R] | 194.127.179.220 (2)
  - 🇳🇱 NL [R] | 144.31.30.69
  - 🇷🇴 RO [R] | 195.74.93.254
  - 🇷🇴 RO [R] | 195.74.93.254 (2)
  - 🇷🇴 RO [R] | 195.74.93.254 (3)
  - 🇳🇱 NL [R] | 195.184.247.170
  - 🇷🇴 RO [R] | 195.74.93.254 (4)
  - 🇷🇴 RO [R] | 195.74.93.254 (5)
  - 🇸🇪 SE [R][grpc] | 185.58.115.149
  - 🇸🇪 SE [R] | 70.34.194.57
  - 🇫🇮 FI [R] | 62.60.255.11
  - 🇵🇱 PL [R][xhttp] | 85.158.109.113
  - 🇵🇱 PL [R][grpc] | 138.124.20.201
  - 🇬🇧 GB [R] | 144.31.217.99
  - 🇬🇧 GB [R] | 150.241.101.222
  - 🇱🇻 LV [R] | 185.145.245.113
  - 🇸🇪 SE [R][grpc] | sw-3.coinbridge.nl
  - 🇫🇮 FI [R] | 150.241.71.35
  - 🇬🇧 GB [R] | 2.26.88.109
  - 🇵🇱 PL [R] | pl1.vitok.cc
  - 🇵🇱 PL [R] | 144.31.1.83
  - 🇷🇴 RO [R] | 93.114.194.131
  - 🇵🇱 PL [R][xhttp] | pol6.odavpn.online
  - 🇸🇪 SE [R] | se1.vitok.cc
  - 🇩🇪 DE [R] | 103.109.234.138
  - 🇰🇿 KZ [R] | 38.180.39.171
  - 🇰🇿 KZ [R] | vpnv1.aspidnet.xyz
  - 🇲🇩 MD [R] | md.riotvpn.eu
  - 🇲🇩 MD [R] | md.riotvpn.eu (2)
  - 🇰🇿 KZ [R] | raff-vpn-kz-server1.ru
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🌍 Прокси
  type: select
  proxies:
  - 🚀 Авто-выбор
  - 🇺🇸 US [R][grpc] | 45.90.12.239
  - 🇳🇱 NL [R] | 195.184.247.178
  - 🇳🇱 NL [R] | 194.127.179.220
  - 🇳🇱 NL [R] | 194.127.179.220 (2)
  - 🇳🇱 NL [R] | 144.31.30.69
  - 🇷🇴 RO [R] | 195.74.93.254
  - 🇷🇴 RO [R] | 195.74.93.254 (2)
  - 🇷🇴 RO [R] | 195.74.93.254 (3)
  - 🇳🇱 NL [R] | 195.184.247.170
  - 🇷🇴 RO [R] | 195.74.93.254 (4)
  - 🇷🇴 RO [R] | 195.74.93.254 (5)
  - 🇸🇪 SE [R][grpc] | 185.58.115.149
  - 🇸🇪 SE [R] | 70.34.194.57
  - 🇫🇮 FI [R] | 62.60.255.11
  - 🇵🇱 PL [R][xhttp] | 85.158.109.113
  - 🇵🇱 PL [R][grpc] | 138.124.20.201
  - 🇬🇧 GB [R] | 144.31.217.99
  - 🇬🇧 GB [R] | 150.241.101.222
  - 🇱🇻 LV [R] | 185.145.245.113
  - 🇸🇪 SE [R][grpc] | sw-3.coinbridge.nl
  - 🇫🇮 FI [R] | 150.241.71.35
  - 🇬🇧 GB [R] | 2.26.88.109
  - 🇵🇱 PL [R] | pl1.vitok.cc
  - 🇵🇱 PL [R] | 144.31.1.83
  - 🇷🇴 RO [R] | 93.114.194.131
  - 🇵🇱 PL [R][xhttp] | pol6.odavpn.online
  - 🇸🇪 SE [R] | se1.vitok.cc
  - 🇩🇪 DE [R] | 103.109.234.138
  - 🇰🇿 KZ [R] | 38.180.39.171
  - 🇰🇿 KZ [R] | vpnv1.aspidnet.xyz
  - 🇲🇩 MD [R] | md.riotvpn.eu
  - 🇲🇩 MD [R] | md.riotvpn.eu (2)
  - 🇰🇿 KZ [R] | raff-vpn-kz-server1.ru
rules:
- MATCH,🌍 Прокси
