proxies:
  - name: "🇳🇱 The Netherlands [SNI-RU] stats.vk-portal.net"
    type: vless
    server: 185.82.73.212
    port: 8443
    uuid: "45e3b7ad-03b6-42fc-b616-1e92bdd0a5b3"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "stats.vk-portal.net"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg"
      short-id: "e499f276e7bd6420"
  - name: "[OpenRay] 🇩🇪 DE-3660"
    type: vless
    server: 77.239.125.99
    port: 443
    uuid: "00c49863-6d15-4289-9229-841ee5f7868c"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "sun6-21.userapi.com"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
  - name: "🇫🇷 France [SNI-RU] sun6-21.userapi.com"
    type: vless
    server: 138.124.79.3
    port: 443
    uuid: "c48e01a0-cc71-4bf9-a924-cf398f33e57a"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "sun6-21.userapi.com"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
  - name: "[OpenRay] 🇳🇱 NL-289"
    type: vless
    server: 72.56.70.31
    port: 8443
    uuid: "90c9c25c-df6c-4438-83d3-ef97166a9184"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "sun6-22.userapi.com"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "KBtor6ap1Ml0bjcI_8UgdHhZYVYNOLuuYsuXsQUNGj0"
  - name: "[OpenRay] 🇫🇷 FR-409"
    type: vless
    server: 138.124.79.8
    port: 443
    uuid: "d6b1327d-2bec-4366-a3a1-9b1284f95841"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "sun6-21.userapi.com"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
  - name: "[OpenRay] 🇫🇷 FR-455"
    type: vless
    server: 138.124.79.9
    port: 443
    uuid: "d6b1327d-2bec-4366-a3a1-9b1284f95841"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "sun6-21.userapi.com"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: "6ba85179e30d4fc2"
  - name: "[🇳🇱] [vl-re-ra] [260125-103552.310]"
    type: vless
    server: 94.103.1.230
    port: 443
    uuid: "d6b1327d-2bec-4366-a3a1-9b1284f95841"
    network: "raw"
    flow: "xtls-rprx-vision"
    servername: "sun6-21.userapi.com"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
  - name: "🇫🇷 France [SNI-RU] sun6-21.userapi.com"
    type: vless
    server: 138.124.79.4
    port: 443
    uuid: "c48e01a0-cc71-4bf9-a924-cf398f33e57a"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "sun6-21.userapi.com"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
  - name: "🇳🇱 The Netherlands [SNI-RU] stats.vk-portal.net"
    type: vless
    server: nl01-ss01.tcp-reset-club.net
    port: 8443
    uuid: "45e3b7ad-03b6-42fc-b616-1e92bdd0a5b3"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "stats.vk-portal.net"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg"
      short-id: "e499f276e7bd6420"
  - name: "[OpenRay] 🇪🇪 EE-10"
    type: vless
    server: 185.155.96.155
    port: 8443
    uuid: "45e3b7ad-03b6-42fc-b616-1e92bdd0a5b3"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "stats.vk-portal.net"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg"
      short-id: "86e999a2cdc2"
  - name: "[OpenRay] 🇵🇱 PL-192"
    type: vless
    server: 151.115.123.227
    port: 8443
    uuid: "45e3b7ad-03b6-42fc-b616-1e92bdd0a5b3"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "stats.vk-portal.net"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg"
      short-id: "e499f276e7bd6420"
  - name: "🇵🇱 Poland [SNI-RU] stats.vk-portal.net"
    type: vless
    server: pol01-ss01.tcp-reset-club.net
    port: 8443
    uuid: "45e3b7ad-03b6-42fc-b616-1e92bdd0a5b3"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "stats.vk-portal.net"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg"
      short-id: "e499f276e7bd6420"
  - name: "🇩🇪 Germany [SNI-RU] sun6-20.userapi.com"
    type: vless
    server: ll2.takovpn.ru
    port: 8443
    uuid: "9715f993-2a6e-4367-b8dd-98d23b0e41fa"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "sun6-20.userapi.com"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "GacPaW0DxNTA8vpoEv7CpGBAu_atzYMBaryAuwcw70M"
      short-id: "6698"
  - name: "🇰🇿 KZ | 91.217.10.166"
    type: vless
    server: 91.217.10.166
    port: 9443
    uuid: "5b6e9a8d-1559-4abc-96ee-a0b98fad5db9"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "api.avito.ru"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "WvNaAxI0W__qfUKbtysH4IwF155YENlv3PG6crCmPkA"

proxy-groups:
  - name: auto
    type: select
    proxies:
      - "🇳🇱 The Netherlands [SNI-RU] stats.vk-portal.net"
      - "[OpenRay] 🇩🇪 DE-3660"
      - "🇫🇷 France [SNI-RU] sun6-21.userapi.com"
      - "[OpenRay] 🇳🇱 NL-289"
      - "[OpenRay] 🇫🇷 FR-409"
      - "[OpenRay] 🇫🇷 FR-455"
      - "[🇳🇱] [vl-re-ra] [260125-103552.310]"
      - "🇫🇷 France [SNI-RU] sun6-21.userapi.com"
      - "🇳🇱 The Netherlands [SNI-RU] stats.vk-portal.net"
      - "[OpenRay] 🇪🇪 EE-10"
      - "[OpenRay] 🇵🇱 PL-192"
      - "🇵🇱 Poland [SNI-RU] stats.vk-portal.net"
      - "🇩🇪 Germany [SNI-RU] sun6-20.userapi.com"
      - "🇰🇿 KZ | 91.217.10.166"

rules:
  - MATCH,auto
