proxies:
  - name: "[OpenRay] 🇳🇱 NL-433"
    type: vless
    server: 185.82.73.212
    port: 8443
    uuid: "45e3b7ad-03b6-42fc-b616-1e92bdd0a5b3"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "stats.vk-portal.net"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg"
      short-id: "e499f276e7bd6420"
  - name: "[OpenRay] 🇳🇱 NL-289"
    type: vless
    server: 72.56.70.31
    port: 8443
    uuid: "90c9c25c-df6c-4438-83d3-ef97166a9184"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "sun6-22.userapi.com"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "KBtor6ap1Ml0bjcI_8UgdHhZYVYNOLuuYsuXsQUNGj0"
  - name: "🇳🇱 The Netherlands [SNI-RU] stats.vk-portal.net"
    type: vless
    server: nl01-ss01.tcp-reset-club.net
    port: 8443
    uuid: "45e3b7ad-03b6-42fc-b616-1e92bdd0a5b3"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "stats.vk-portal.net"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg"
      short-id: "e499f276e7bd6420"
  - name: "🇫🇷[openproxylist.com] vless-FR"
    type: vless
    server: 138.124.79.4
    port: 443
    uuid: "d6b1327d-2bec-4366-a3a1-9b1284f95841"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "sun6-21.userapi.com"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
  - name: "🇫🇷 France [SNI-RU] sun6-21.userapi.com"
    type: vless
    server: 138.124.79.3
    port: 443
    uuid: "d6b1327d-2bec-4366-a3a1-9b1284f95841"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "sun6-21.userapi.com"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: "6ba85179e30d4fc2"
  - name: "🇳🇱 The Netherlands [SNI-RU] sun6-22.userapi.com"
    type: vless
    server: 144.124.242.141
    port: 443
    uuid: "2dd1a15d-1426-413a-a3b8-a645788bc844"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "sun6-22.userapi.com"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "kY32I2PvI5UYqhjoZlcL0z6V6r1AV_lLZolQH78ApmU"
      short-id: "ae575a16aa1a19a9"
  - name: "🇫🇷 France [SNI-RU] sun6-21.userapi.com"
    type: vless
    server: 138.124.79.9
    port: 443
    uuid: "c48e01a0-cc71-4bf9-a924-cf398f33e57a"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "sun6-21.userapi.com"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
  - name: "🇫🇷 France [SNI-RU] sun6-21.userapi.com"
    type: vless
    server: 138.124.79.8
    port: 443
    uuid: "d6b1327d-2bec-4366-a3a1-9b1284f95841"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "sun6-21.userapi.com"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
  - name: "[OpenRay] 🇪🇪 EE-10"
    type: vless
    server: 185.155.96.155
    port: 8443
    uuid: "45e3b7ad-03b6-42fc-b616-1e92bdd0a5b3"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "stats.vk-portal.net"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg"
      short-id: "86e999a2cdc2"
  - name: "🇪🇪 Estonia — #434"
    type: vless
    server: 23.230.179.116
    port: 443
    uuid: "2dd1a15d-1426-413a-a3b8-a645788bc844"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "eh.vk.com"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "J2yJCkBI-GDKHgH0OuRP0Bm0aqZ8qL_fXhITn4titAg"
      short-id: "a20d3ed244c76426"
  - name: "[OpenRay] 🇵🇱 PL-192"
    type: vless
    server: 151.115.123.227
    port: 8443
    uuid: "45e3b7ad-03b6-42fc-b616-1e92bdd0a5b3"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "stats.vk-portal.net"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg"
      short-id: "e499f276e7bd6420"
  - name: "🇵🇱 Poland [SNI-RU] stats.vk-portal.net"
    type: vless
    server: pol01-ss01.tcp-reset-club.net
    port: 8443
    uuid: "45e3b7ad-03b6-42fc-b616-1e92bdd0a5b3"
    network: "tcp"
    flow: "xtls-rprx-vision"
    servername: "stats.vk-portal.net"
    client-fingerprint: chrome
    encryption: "none"
    tls: true
    udp: true
    reality-opts:
      public-key: "mLmBhbVFfNuo2eUgBh6r9-5Koz9mUCn3aSzlR6IejUg"
      short-id: "e499f276e7bd6420"

proxy-groups:
  - name: auto
    type: select
    proxies:
      - "[OpenRay] 🇳🇱 NL-433"
      - "[OpenRay] 🇳🇱 NL-289"
      - "🇳🇱 The Netherlands [SNI-RU] stats.vk-portal.net"
      - "🇫🇷[openproxylist.com] vless-FR"
      - "🇫🇷 France [SNI-RU] sun6-21.userapi.com"
      - "🇳🇱 The Netherlands [SNI-RU] sun6-22.userapi.com"
      - "🇫🇷 France [SNI-RU] sun6-21.userapi.com"
      - "🇫🇷 France [SNI-RU] sun6-21.userapi.com"
      - "[OpenRay] 🇪🇪 EE-10"
      - "🇪🇪 Estonia — #434"
      - "[OpenRay] 🇵🇱 PL-192"
      - "🇵🇱 Poland [SNI-RU] stats.vk-portal.net"

rules:
  - MATCH,auto
